<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RoboMouse.Core</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
    <Version>1.1.1</Version>
    <Authors>Tim Dodd</Authors>
    <Product>RoboMouse</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoboMouse.Contracts\RoboMouse.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="RoboMouse.Core.Tests" />
  </ItemGroup>

</Project>
