<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <RootNamespace>RoboMouse.Core</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>0.1.0</Version>
    <Authors>Tim Dodd</Authors>
    <Product>RoboMouse</Product>
  </PropertyGroup>

</Project>
