<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>RoboMouse.App</RootNamespace>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Version>1.0.0</Version>
    <Authors>Tim Dodd</Authors>
    <Product>RoboMouse</Product>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\offline.ico" LogicalName="RoboMouse.App.Assets.offline.ico" />
    <EmbeddedResource Include="Assets\online.ico" LogicalName="RoboMouse.App.Assets.online.ico" />
    <EmbeddedResource Include="Assets\controlling.ico" LogicalName="RoboMouse.App.Assets.controlling.ico" />
    <EmbeddedResource Include="Assets\controlled.ico" LogicalName="RoboMouse.App.Assets.controlled.ico" />
    <EmbeddedResource Include="Assets\disabled.ico" LogicalName="RoboMouse.App.Assets.disabled.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoboMouse.Core\RoboMouse.Core.csproj" />
  </ItemGroup>

</Project>
